
# SEO settings
title: "Project Ka"
title2: "space" # default: ""
description: "Just another minimalist Jekyll theme for technical writing."
keywords: "Jekyll, theme, free, download, SEO, blog, web, minimalist, thinkspace"
url: http://ignaciogrubio.github.io
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: http://github.com/heiswayi/thinkspace
disqus_shortname: "hnbloggithub"
twitter_username: "IgnacioGRubio"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Ka"
  job      : ""
  bio      : ""
  thumb    : 
  email    : mail@ignaciogrubio.com
  url      : http://ignaciogrubio.github.io
  github   : http://github.com/ignaciogrubio
  twitter  : http://twitter.com/ignaciogrubio
  facebook : 
  linkedin : 

# social settings
og_locale: "es_ES"
twitter_card: "summary_large_image"
twitter_site: "@IgnacioGRubio"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
