
# SEO settings
title: "Project"
title2: " Ka"
description: "My Blog"
keywords: "Blog, ignaciogrubio, technology, smartphone, pc"
url: http://ignaciogrubio.github.io
baseurl: ""

google_analytics: UA-XXXXX-XX
repo: http://ignaciogrubio.github.io
disqus_shortname: "glitched-1"
twitter_username: "IgnacioGRubio"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Ka"
  job      : ""
  bio      : ""
  thumb    :
  email    : mail@ignaciogrubio.com
  url      : http://ignaciogrubio.github.io
  github   : http://github.com/ignaciogrubio
  twitter  : http://twitter.com/ignaciogrubio
  facebook :
  linkedin :

# social settings
og_locale: "es_ES"
twitter_card: "summary_large_image"
twitter_site: "@IgnacioGRubio"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog


exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
